"""
Snapshots of every major evidence state, at mobile width.

These are **renderable HTML files**, not images. There is no browser in this
environment, so a PNG would have to be produced elsewhere and would drift from
the code silently; a committed HTML file is generated by the same functions the
application calls, is diffed in review like any other snapshot, and can be
opened in a browser at 320px to see the actual state.

Each file is a complete standalone page carrying the production CSS extracted
from ``app.py``, so what a reviewer opens is what a patient sees. The extraction
is asserted rather than duplicated: if the CSS in ``app.py`` changes, these files
change with it, and if the extraction stops finding it the test fails.

Regenerate with ``SYNAPSE_UPDATE_SNAPSHOTS=1 pytest``, then **open the files and
look at them** before committing. That is the point of the exercise; a snapshot
regenerated without being read is worse than none.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

import pytest

from synapse.answer.policy import apply, decide
from synapse.answer.render import (
    PERMANENT_DISCLAIMER,
    SourceNumbering,
    render_answer_html,
    render_failure_html,
)
from synapse.answer.schema import (
    AnswerAction,
    GroundedAnswer,
    GroundedClaim,
    SupportingExcerpt,
)
from synapse.answer.verify import RetrievedEvidence, verify_answer
from synapse.evidence.insufficient import InsufficientEvidence, InsufficientReason
from synapse.evidence.metadata import MetadataResolver
from synapse.evidence.render import render_insufficient_html, render_review_evidence_card
from synapse.ui.errors import PATIENT_ERROR_MESSAGE

REPO_ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT_DIR = REPO_ROOT / "docs" / "snapshots"
PACK_DIR = REPO_ROOT / "source_packs" / "diabetes-previsit"

CHUNK_TEXT = (
    "HbA1c reflects average plasma glucose over 2-3 months. "
    "A target below 7% is appropriate for most non-pregnant adults with diabetes."
)
OTHER_CHUNK = "Regular review supports earlier detection of complications in long-term conditions."

EVIDENCE = RetrievedEvidence(
    chunk_texts={
        "example:diabetes-0001#0000": CHUNK_TEXT,
        "example:diabetes-0002#0000": OTHER_CHUNK,
    },
    source_ids=frozenset({"example:diabetes-0001", "example:diabetes-0002"}),
    source_titles={
        "example:diabetes-0001": "What HbA1c measures",
        "example:diabetes-0002": "Routine diabetes review",
    },
    source_urls={
        "example:diabetes-0001": "https://example.org/synthetic-source/0001",
        "example:diabetes-0002": "https://example.org/synthetic-source/0002",
    },
)
SOURCE_ORDER = ["example:diabetes-0001", "example:diabetes-0002"]


def extract_css() -> str:
    """Pull the production stylesheet out of app.py.

    Extracted rather than copied so a snapshot cannot drift from the interface
    it claims to depict.

    The palette block is injected by the app through an f-string, so the source
    contains the literal text ``{css_variables()}``. Substituting the real
    tokens matters more than it looks: left as-is it is invalid CSS, the parser
    swallows the rules that follow it while resynchronising, and every
    ``var(--token)`` resolves to nothing. That silently disabled the focus
    outline in the snapshots, which the browser tests then correctly reported as
    an accessibility failure.
    """
    from synapse.a11y.palette import css_variables

    source = (REPO_ROOT / "app.py").read_text(encoding="utf-8")
    blocks = re.findall(r"<style>(.*?)</style>", source, re.DOTALL)
    assert blocks, "no <style> block found in app.py; the snapshot extraction is broken"
    stylesheet = "\n".join(blocks).replace("{css_variables()}", css_variables())
    assert "--focus-ring" in stylesheet, "the palette did not reach the snapshot stylesheet"
    return stylesheet


def page(title: str, body: str, *, width: int = 320) -> str:
    """Wrap a fragment in a standalone page at a fixed mobile width."""
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Synapse — {title}</title>
<style>{extract_css()}</style>
<style>
  /* Snapshot harness only: pins the viewport to the narrowest supported width
     so a reviewer sees the mobile layout without resizing anything. */
  /* border-box and no body padding: the frame must fit the viewport it names,
     or a reflow test measures the harness rather than the interface. */
  * {{ box-sizing: border-box; }}
  body {{ background:#05030D; margin:0; padding:0; font-family:'Inter Tight',system-ui,sans-serif; }}
  .snapshot-frame {{ width:100%; max-width:{width}px; margin:0 auto; border:1px dashed #3a3a5c; padding:8px; }}
  .snapshot-caption {{ color:#a8a8c0; font-size:12px; text-align:center; padding:8px 4px; }}
</style>
</head><body>
<div class="snapshot-caption">{title} — rendered at {width}px</div>
<div class="snapshot-frame">{body}</div>
</body></html>
"""


def assert_snapshot(name: str, actual: str) -> None:
    """Compare against a committed snapshot, or write it on first run."""
    SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)
    path = SNAPSHOT_DIR / f"{name}.html"
    if os.environ.get("SYNAPSE_UPDATE_SNAPSHOTS") == "1":
        path.write_text(actual, encoding="utf-8")
        return
    if not path.is_file():
        path.write_text(actual, encoding="utf-8")
        pytest.fail(f"snapshot '{name}' did not exist and has been written; open it, then re-run")
    expected = path.read_text(encoding="utf-8")
    assert actual == expected, (
        f"rendered output changed for '{name}'. This is patient-facing. "
        "Open docs/snapshots/ and look at the change before regenerating."
    )


def resolver() -> MetadataResolver:
    """The real governed pack."""
    return MetadataResolver.from_directory(PACK_DIR)


def a_claim(claim_id: str, text: str, source_id: str, quote: str) -> GroundedClaim:
    """A claim citing the example pack."""
    return GroundedClaim(
        claim_id=claim_id,
        text=text,
        source_ids=[source_id],
        supporting_excerpts=[
            SupportingExcerpt(source_id=source_id, chunk_id=f"{source_id}#0000", quote=quote)
        ],
    )


def displayed(*claims: GroundedClaim, action: AnswerAction = AnswerAction.ANSWER) -> GroundedAnswer:
    """Verify and gate, exactly as the application does."""
    answer = GroundedAnswer(
        summary="Your HbA1c test shows your average blood sugar over the past two to three months.",
        claims=list(claims),
        doctor_evaluation="Your clinician will look at this alongside your history and treatment.",
        questions_for_doctor=[
            "What does my result mean for me specifically?",
            "How often should this be rechecked?",
        ],
        limitations=[
            "This is general information from published research, not advice about your own care."
        ],
        action=action,
    )
    verified, report = verify_answer(answer, EVIDENCE)
    return apply(verified, decide(verified, report))


class TestMobileStateSnapshots:
    """One file per major state, all at 320px."""

    def _numbering(self) -> SourceNumbering:
        return SourceNumbering.from_evidence(
            EVIDENCE, SOURCE_ORDER, {"example:diabetes-0001": 0.86, "example:diabetes-0002": 0.71}
        )

    def test_success_state(self) -> None:
        answer = displayed(
            a_claim(
                "c1",
                "HbA1c reflects average plasma glucose over 2-3 months.",
                "example:diabetes-0001",
                "HbA1c reflects average plasma glucose over 2-3 months",
            ),
            a_claim(
                "c2",
                "Regular review supports earlier detection of complications.",
                "example:diabetes-0002",
                "Regular review supports earlier detection of complications",
            ),
        )
        html = render_answer_html(answer, self._numbering(), resolver=resolver())
        assert_snapshot("state-success", page("Answer with evidence", html))

    def test_success_state_expanded(self) -> None:
        # The same page with the disclosures open, so a reviewer sees the
        # evidence cards without having to click each one.
        answer = displayed(
            a_claim(
                "c1",
                "HbA1c reflects average plasma glucose over 2-3 months.",
                "example:diabetes-0001",
                "HbA1c reflects average plasma glucose over 2-3 months",
            )
        )
        html = render_answer_html(answer, self._numbering(), resolver=resolver())
        assert_snapshot(
            "state-success-evidence-open",
            page("Evidence card, expanded", html.replace("<details ", "<details open ")),
        )

    def test_partially_supported_state(self) -> None:
        answer = displayed(
            a_claim(
                "c1",
                "A target below 8% is appropriate for most adults.",
                "example:diabetes-0001",
                "A target below 7%",
            )
        )
        html = render_answer_html(answer, self._numbering(), resolver=resolver())
        assert_snapshot("state-partially-supported", page("Partly verified claim", html))

    @pytest.mark.parametrize("reason", list(InsufficientReason))
    def test_insufficient_states(self, reason: InsufficientReason) -> None:
        body = (
            render_insufficient_html(
                InsufficientEvidence(reason, pack_id="diabetes-previsit", pack_version="0.1.0")
            )
            + f'<div class="disclaimer-permanent">{PERMANENT_DISCLAIMER}</div>'
        )
        assert_snapshot(
            f"state-insufficient-{reason.value.replace('_', '-')}",
            page(f"Insufficient evidence — {reason.value}", body),
        )

    def test_abstain_state(self) -> None:
        answer = displayed(
            a_claim("c1", "An unsupported assertion.", "example:diabetes-0001", "not in the source")
        )
        assert answer.action is AnswerAction.ABSTAIN
        body = render_insufficient_html(
            InsufficientEvidence(InsufficientReason.BELOW_THRESHOLD)
        ) + render_answer_html(answer, self._numbering(), resolver=resolver())
        assert_snapshot("state-abstain", page("Abstention", body))

    def test_emergency_state(self) -> None:
        html = render_answer_html(
            displayed(action=AnswerAction.EMERGENCY), self._numbering(), resolver=resolver()
        )
        assert_snapshot("state-emergency", page("Emergency routing", html))

    def test_error_state(self) -> None:
        html = render_failure_html(PATIENT_ERROR_MESSAGE, "generation_unavailable")
        assert_snapshot("state-error", page("Service failure", html))

    def test_empty_state(self) -> None:
        body = (
            '<div class="empty-hint">Describe your symptoms or ask anything<br>'
            "you want to understand before seeing your doctor.</div>"
        )
        assert_snapshot("state-empty", page("Empty — before any question", body))

    def test_loading_state(self) -> None:
        body = (
            '<div class="bubble-user">why is my blood sugar high in the mornings?</div>'
            '<div class="resp-card"><div class="card-label">Searching relevant research…</div>'
            '<div class="card-body">Synapse is searching published research. '
            "This usually takes a few seconds.</div></div>"
        )
        assert_snapshot("state-loading", page("Loading", body))

    def test_review_view_state(self) -> None:
        # Superseded and unreviewed sources, visible only here.
        cards = "".join(
            render_review_evidence_card(metadata)
            for metadata in sorted(
                resolver().by_document.values(), key=lambda item: item.document_id
            )
        )
        assert_snapshot(
            "state-review-view", page("Review view (not patient-facing)", cards, width=360)
        )


class TestSnapshotsStayHonest:
    """The snapshots must depict the real interface."""

    def test_the_css_is_extracted_from_the_application(self) -> None:
        css = extract_css()
        for selector in (".ev-summary", ".ev-card", ".insufficient-card", ".visually-hidden"):
            assert selector in css

    def test_every_snapshot_carries_the_production_stylesheet(self) -> None:
        for path in SNAPSHOT_DIR.glob("state-*.html"):
            text = path.read_text(encoding="utf-8")
            assert ".ev-summary" in text, f"{path.name} was generated without the app stylesheet"

    def test_no_snapshot_contains_a_real_patient_query(self) -> None:
        # The snapshots are committed and public; their content is authored.
        for path in SNAPSHOT_DIR.glob("state-*.html"):
            text = path.read_text(encoding="utf-8").lower()
            assert "sk-" not in text
            assert "api_key" not in text

    def test_every_major_state_has_a_snapshot(self) -> None:
        expected = {
            "state-success",
            "state-success-evidence-open",
            "state-partially-supported",
            "state-abstain",
            "state-emergency",
            "state-error",
            "state-empty",
            "state-loading",
            "state-review-view",
        } | {
            f"state-insufficient-{reason.value.replace('_', '-')}" for reason in InsufficientReason
        }
        present = {path.stem for path in SNAPSHOT_DIR.glob("state-*.html")}
        assert expected <= present, f"missing snapshots: {sorted(expected - present)}"
