"""
Browser-based accessibility checks: axe-core, keyboard flow, zoom, reflow.

These cover what markup parsing cannot: computed contrast, focus order, visible
focus, reflow at 320px and 200% zoom, and whether a control can actually be
reached with a keyboard. They need a real browser, so they **skip cleanly** when
Playwright or Chrome is unavailable rather than failing a run that has nothing
wrong with it.

Two decisions worth stating:

* **Chrome is driven through the installed channel**, not a downloaded browser.
  It avoids a 150MB fetch per environment, and it tests the engine a patient is
  most likely to be using.
* **The pages under test are the committed state snapshots**, not a live
  Streamlit server. Those files are generated by the same render functions the
  application calls and carry the production stylesheet, so axe sees the real
  markup and the real CSS without needing an API key, a corpus, or a running
  server. Streamlit's own widgets are covered by the live-app test at the
  bottom, which needs no key because it only exercises the empty state.

axe-core ships inside ``axe-core-python``, so no CDN is contacted. Nothing here
touches the network.
"""

from __future__ import annotations

import shutil
import socket
import subprocess
import time
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT_DIR = REPO_ROOT / "docs" / "snapshots"
BRIEF_DIR = SNAPSHOT_DIR / "brief"

playwright = pytest.importorskip("playwright.sync_api", reason="playwright is not installed")
axe_module = pytest.importorskip(
    "axe_core_python.sync_playwright", reason="axe-core-python is not installed"
)

# WCAG 2.2 AA is the target. axe tags map onto the specification, and restricting
# the run to these keeps best-practice advisories out of a pass/fail gate.
AXE_TAGS = ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa", "wcag22aa"]

# Rules disabled with a stated reason, rather than silently.
DISABLED_RULES = {
    # The snapshot harness renders a fragment inside a plain wrapper, so there
    # is no page-level landmark structure to find. Landmarks are checked on the
    # live app instead.
    "region": "fragments are rendered standalone in the snapshot harness",
    "page-has-heading-one": "fragments sit under the application's h1, which is not in the fragment",
    "html-has-lang": "the harness page sets lang; fragments do not carry it",
}


@pytest.fixture(scope="module")
def browser():
    """A Chrome instance, or a skip if none is available."""
    from playwright.sync_api import sync_playwright

    with sync_playwright() as engine:
        try:
            instance = engine.chromium.launch(channel="chrome")
        except Exception as exc:  # No Chrome on this machine
            pytest.skip(f"no Chrome available: {type(exc).__name__}")
        yield instance
        instance.close()


def run_axe(page) -> list[dict]:
    """Run axe against the current page and return AA violations."""
    from axe_core_python.sync_playwright import Axe

    # Rules are filtered in Python rather than disabled through axe options:
    # the options dict is interpolated into JavaScript, where a Python ``False``
    # is a ReferenceError. Filtering here is also more transparent, since the
    # reason for each exclusion sits beside the exclusion.
    results = Axe().run(page, options={"runOnly": {"type": "tag", "values": AXE_TAGS}})
    return [
        violation
        for violation in results.get("violations", [])
        if violation["id"] not in DISABLED_RULES
    ]


def describe(violations: list[dict]) -> str:
    """A readable failure message."""
    lines = []
    for violation in violations:
        targets = ", ".join(str(node.get("target")) for node in violation.get("nodes", [])[:3])
        lines.append(f"{violation['id']} ({violation['impact']}): {violation['help']} -> {targets}")
    return "\n".join(lines)


# Selectors Streamlit owns. A violation whose every node sits inside one of
# these is a framework issue: it cannot be fixed from app.py, and failing the
# build on it would mean either patching a vendor's DOM or switching the check
# off entirely.
FRAMEWORK_SELECTORS = (
    ".stSidebar",
    ".stAppHeader",
    "[data-testid^='st']",
    "[data-baseweb",
    "#MainMenu",
    ".stToolbar",
    "header",
)


def is_framework_node(node: dict) -> bool:
    """True when a violating node belongs to Streamlit rather than to Synapse."""
    target = " ".join(str(part) for part in node.get("target", []))
    return any(selector.strip("[]'") in target for selector in FRAMEWORK_SELECTORS)


def partition_violations(violations: list[dict]) -> tuple[list[dict], list[dict]]:
    """Split findings into ours and the framework's."""
    ours, framework = [], []
    for violation in violations:
        nodes = violation.get("nodes", [])
        (framework if nodes and all(is_framework_node(node) for node in nodes) else ours).append(
            violation
        )
    return ours, framework


def snapshot_pages() -> list[Path]:
    """Every committed state snapshot."""
    return sorted(SNAPSHOT_DIR.glob("state-*.html")) + sorted(BRIEF_DIR.glob("brief-*.html"))


class TestAxeOnEveryState:
    """axe-core over each committed state."""

    @pytest.mark.parametrize("path", snapshot_pages(), ids=lambda path: path.stem)
    def test_no_wcag_aa_violations(self, browser, path: Path) -> None:
        page = browser.new_page()
        try:
            page.goto(path.as_uri())
            violations = run_axe(page)
            assert violations == [], f"{path.name}:\n{describe(violations)}"
        finally:
            page.close()

    @pytest.mark.parametrize(
        "width,height", [(320, 720), (375, 812), (768, 1024)], ids=["320px", "375px", "768px"]
    )
    def test_no_violations_at_mobile_widths(self, browser, width: int, height: int) -> None:
        page = browser.new_page(viewport={"width": width, "height": height})
        try:
            page.goto((SNAPSHOT_DIR / "state-success-evidence-open.html").as_uri())
            violations = run_axe(page)
            assert violations == [], f"{width}px:\n{describe(violations)}"
        finally:
            page.close()


class TestReflow:
    """1.4.10: no horizontal scrolling at 320px, and 200% zoom."""

    @pytest.mark.parametrize("path", snapshot_pages(), ids=lambda path: path.stem)
    def test_no_horizontal_scroll_at_320px(self, browser, path: Path) -> None:
        page = browser.new_page(viewport={"width": 320, "height": 720})
        try:
            page.goto(path.as_uri())
            overflow = page.evaluate(
                "() => document.documentElement.scrollWidth - document.documentElement.clientWidth"
            )
            # A couple of pixels of rounding is tolerable; a scrollbar is not.
            assert overflow <= 2, f"{path.name} scrolls horizontally by {overflow}px at 320px"
        finally:
            page.close()

    def test_content_reflows_at_200_percent_zoom(self, browser) -> None:
        # 1.4.4 measured the way the specification frames it: 1280 CSS pixels at
        # 200% behaves as a 640px viewport.
        page = browser.new_page(viewport={"width": 640, "height": 512})
        try:
            page.goto((SNAPSHOT_DIR / "state-success-evidence-open.html").as_uri())
            overflow = page.evaluate(
                "() => document.documentElement.scrollWidth - document.documentElement.clientWidth"
            )
            assert overflow <= 2, f"content does not reflow at 200% zoom (overflow {overflow}px)"
        finally:
            page.close()


class TestKeyboardOnly:
    """2.1.1, 2.1.2, 2.4.7."""

    def test_the_evidence_disclosure_opens_with_the_keyboard(self, browser) -> None:
        page = browser.new_page()
        try:
            page.goto((SNAPSHOT_DIR / "state-success.html").as_uri())
            summary = page.locator("summary.ev-summary").first
            summary.focus()
            assert page.evaluate("() => document.activeElement.tagName.toLowerCase()") == "summary"
            opened_before = page.locator("details.ev-details").first.evaluate("el => el.open")
            page.keyboard.press("Enter")
            opened_after = page.locator("details.ev-details").first.evaluate("el => el.open")
            assert opened_before is False and opened_after is True
        finally:
            page.close()

    def test_the_disclosure_closes_again(self, browser) -> None:
        page = browser.new_page()
        try:
            page.goto((SNAPSHOT_DIR / "state-success.html").as_uri())
            details = page.locator("details.ev-details").first
            page.locator("summary.ev-summary").first.focus()
            page.keyboard.press("Enter")
            page.keyboard.press("Enter")
            assert details.evaluate("el => el.open") is False
        finally:
            page.close()

    def test_tabbing_reaches_every_interactive_element(self, browser) -> None:
        page = browser.new_page()
        try:
            page.goto((SNAPSHOT_DIR / "state-success-evidence-open.html").as_uri())
            expected = page.locator("summary, a[href], button").count()
            seen = set()
            for _ in range(expected * 3):  # Generous: proves no trap, not exact count
                page.keyboard.press("Tab")
                marker = page.evaluate(
                    "() => { const el = document.activeElement;"
                    " return el ? el.tagName + ':' + (el.textContent||'').slice(0,24) : ''; }"
                )
                if marker:
                    seen.add(marker)
            assert len(seen) >= expected, f"reached {len(seen)} of {expected} interactive elements"
        finally:
            page.close()

    def test_there_is_no_keyboard_trap(self, browser) -> None:
        # Tab repeatedly; focus must eventually leave the document (wrap to the
        # browser chrome), which manifests as activeElement returning to body.
        page = browser.new_page()
        try:
            page.goto((SNAPSHOT_DIR / "state-success-evidence-open.html").as_uri())
            returned_to_body = False
            for _ in range(60):
                page.keyboard.press("Tab")
                if page.evaluate("() => document.activeElement === document.body"):
                    returned_to_body = True
                    break
            assert returned_to_body, "focus never left the last control; possible keyboard trap"
        finally:
            page.close()

    def test_focus_is_visible(self, browser) -> None:
        page = browser.new_page()
        try:
            page.goto((SNAPSHOT_DIR / "state-success.html").as_uri())
            summary = page.locator("summary.ev-summary").first
            summary.focus()
            outline = summary.evaluate(
                "el => { const s = getComputedStyle(el);"
                " return {w: s.outlineWidth, style: s.outlineStyle}; }"
            )
            assert outline["style"] != "none", "focused control has no outline"
            assert float(outline["w"].replace("px", "")) >= 2, f"focus ring too thin: {outline}"
        finally:
            page.close()


class TestReducedMotion:
    """2.3.3."""

    def test_animation_is_disabled_under_reduced_motion(self, browser) -> None:
        context = browser.new_context(reduced_motion="reduce")
        page = context.new_page()
        try:
            page.goto((SNAPSHOT_DIR / "state-success.html").as_uri())
            durations = page.evaluate(
                "() => Array.from(document.querySelectorAll('*'))"
                ".flatMap(el => getComputedStyle(el).animationDuration.split(', '))"
            )

            def seconds(value: str) -> float:
                """Parse a computed duration. 0.01ms computes as '1e-05s'."""
                text = value.strip()
                if text.endswith("ms"):
                    return float(text[:-2]) / 1000
                if text.endswith("s"):
                    return float(text[:-1])
                return 0.0

            # The media query collapses every animation to 0.01ms, which the
            # browser reports as '1e-05s'. Anything a person could perceive is
            # a failure; anything below ~50ms is effectively off.
            perceptible = [value for value in durations if seconds(value) > 0.05]
            assert perceptible == [], (
                f"animations still running under reduced motion: {sorted(set(perceptible))}"
            )
        finally:
            page.close()
            context.close()

    def test_animation_runs_when_motion_is_allowed(self, browser) -> None:
        # Guard the guard: if nothing animates either way, the test above proves
        # nothing.
        context = browser.new_context(reduced_motion="no-preference")
        page = context.new_page()
        try:
            page.goto((SNAPSHOT_DIR / "state-success.html").as_uri())
            has_transition = page.evaluate(
                "() => Array.from(document.querySelectorAll('*'))"
                ".some(el => { const d = getComputedStyle(el).transitionDuration;"
                " return d && d !== '0s'; })"
            )
            assert has_transition, "nothing animates at all, so the reduced-motion test is vacuous"
        finally:
            page.close()
            context.close()


class TestAudioNeverPlays:
    """1.4.2, verified in a browser rather than by reading the source."""

    def test_no_audio_context_is_created(self, browser) -> None:
        page = browser.new_page()
        try:
            page.add_init_script(
                "window.__audioCreated = false;"
                "const R = window.AudioContext;"
                "window.AudioContext = function(...a){ window.__audioCreated = true; return new R(...a); };"
            )
            page.goto((SNAPSHOT_DIR / "state-success.html").as_uri())
            page.wait_for_timeout(400)
            assert page.evaluate("() => window.__audioCreated") is False
        finally:
            page.close()


def _free_port() -> int:
    """An unused localhost port."""
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        return probe.getsockname()[1]


@pytest.fixture(scope="module")
def streamlit_server():
    """Run the real app on localhost, or skip.

    Only the empty state is exercised, so no API key, corpus or index is needed
    and no network call is made.
    """
    port = _free_port()
    streamlit_binary = shutil.which("streamlit")
    if streamlit_binary is None:
        pytest.skip("streamlit is not on PATH")
    # Fixed argument list, absolute binary, no shell: nothing here is
    # attacker-influenced, and resolving the path satisfies the linter's
    # partial-executable rule rather than suppressing it.
    process = subprocess.Popen(  # noqa: S603
        [
            streamlit_binary,
            "run",
            "app.py",
            "--server.port",
            str(port),
            "--server.headless",
            "true",
            "--browser.gatherUsageStats",
            "false",
        ],
        cwd=REPO_ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        env={**__import__("os").environ, "SYNAPSE_TELEMETRY": "0"},
    )
    url = f"http://127.0.0.1:{port}"
    for _ in range(60):
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=0.5):
                break
        except OSError:
            time.sleep(0.5)
    else:
        process.terminate()
        pytest.skip("streamlit did not start")
    time.sleep(2)  # Let the first script run finish
    yield url
    # Streamlit does not always exit on SIGTERM within a sensible window, and a
    # teardown that raises turns a passing suite red.
    process.terminate()
    try:
        process.wait(timeout=10)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=10)


@pytest.mark.slow
class TestLiveApplication:
    """The real Streamlit page, empty state only."""

    def test_the_question_field_has_a_visible_label(self, browser, streamlit_server) -> None:
        page = browser.new_page()
        try:
            page.goto(streamlit_server, wait_until="networkidle")
            page.wait_for_selector("textarea", timeout=15000)
            label = page.get_by_text("Your question or symptoms").first
            assert label.is_visible(), "the question field has no visible label"
        finally:
            page.close()

    def test_the_skip_link_is_reachable_early_and_visible_on_focus(
        self, browser, streamlit_server
    ) -> None:
        """The skip link cannot be literally first, and that is a Streamlit limit.

        Streamlit renders its own header, toolbar and sidebar before any
        application content, with no supported way to insert markup ahead of
        them. So the requirement is that the link is reachable within a short
        run of tab stops and becomes visible when focused, not that it is stop
        number one.

        Reachability is asserted on element identity rather than on the text of
        ``document.activeElement``: Streamlit wraps markdown in containers whose
        textContent includes the link, so a text match reports success while
        focus is still on a wrapper.
        """
        page = browser.new_page()
        try:
            page.goto(streamlit_server, wait_until="networkidle")
            page.wait_for_selector("textarea", timeout=15000)

            found_at = None
            for index in range(1, 16):
                page.keyboard.press("Tab")
                if page.evaluate(
                    "() => document.activeElement === document.querySelector('a.skip-link')"
                ):
                    found_at = index
                    break
            assert found_at is not None, "the skip link was not reachable in the first 15 tab stops"

            # Focused, it must come on-screen; unfocused it stays out of the way.
            offset = page.evaluate(
                "() => { const a = document.querySelector('a.skip-link');"
                " a.focus(); return a.getBoundingClientRect().x; }"
            )
            assert offset >= -1, f"the skip link stays off-screen when focused (x={offset})"
        finally:
            page.close()

    def test_a_collapsed_sidebar_is_not_in_the_tab_order(self, browser, streamlit_server) -> None:
        """Focus must not land on controls the user cannot see.

        A collapsed Streamlit sidebar is moved off-screen with a transform but
        keeps visibility:visible, so its API key field, its checkbox and its
        buttons stayed focusable at x=-305. Eight invisible stops on a phone,
        before anything perceivable. The fix is a visibility rule keyed on
        aria-expanded, which Streamlit already sets.
        """
        page = browser.new_page(viewport={"width": 390, "height": 800})
        try:
            page.goto(streamlit_server, wait_until="networkidle")
            page.wait_for_selector("textarea", timeout=15000)
            focusable_in_sidebar = page.evaluate(
                "() => { const s = document.querySelector('[data-testid=\"stSidebar\"]');"
                " if (!s) return 0;"
                " if (getComputedStyle(s).visibility === 'hidden') return 0;"
                " return s.querySelectorAll('input, textarea, select, button, a[href]').length; }"
            )
            assert focusable_in_sidebar == 0, (
                f"{focusable_in_sidebar} controls in the collapsed sidebar are still focusable"
            )
        finally:
            page.close()

    def test_no_axe_violations_on_the_empty_state(self, browser, streamlit_server) -> None:
        page = browser.new_page()
        try:
            page.goto(streamlit_server, wait_until="networkidle")
            page.wait_for_selector("textarea", timeout=15000)
            ours, framework = partition_violations(run_axe(page))
            # Framework findings are reported, not asserted: they sit in
            # Streamlit's own DOM, cannot be fixed from app.py, and are listed
            # with a remediation route in docs/accessibility.md §8. Failing the
            # build on them would mean patching a vendor's markup or switching
            # the check off entirely, and the second always wins eventually.
            if framework:
                print("\nStreamlit framework findings (not fixable from app.py):")
                print(describe(framework))
            assert ours == [], describe(ours)
        finally:
            page.close()
