"""
synapse.schemas.source_pack
===========================
The source pack: a versioned, reviewable collection of medical sources scoped
to one narrowly defined product use.

The distinction this module exists to enforce, stated once:

    **Automated discovery is not clinical approval.**

An ingestion run can establish that a publication exists, is in a topic area,
and carries certain publisher metadata. It cannot establish that the
publication is appropriate for a particular patient population, in a particular
product, for a particular purpose. Only a qualified human reviewer can, and
only by recording *why*.

The schema makes the second thing unconstructible without the first's evidence:
a :class:`PackSource` cannot hold ``lifecycle_state = "approved"`` unless it
also carries a complete :class:`ClinicianReview`, and a
:class:`SourcePackManifest` cannot hold ``approval_state = "approved"`` unless
its scope, reviewer requirements and approval timestamps are all present. There
is no code path that produces an approval as a side effect of anything.

Records are self-contained by design. A reviewer reads ``sources.jsonl`` and
must be able to judge each entry without joining against a corpus artifact, so
bibliographic fields are duplicated into the pack rather than referenced.
"""

from __future__ import annotations  # Postponed annotations

import re  # Semantic-version validation
from datetime import date, datetime
from typing import ClassVar

from pydantic import Field, field_validator, model_validator

from synapse.hashing import is_sha256_hex
from synapse.identifiers import is_valid_document_id, is_valid_reviewer_id
from synapse.schemas.base import SynapseModel, VersionedModel, require_timezone_aware
from synapse.schemas.enums import (
    EvidenceType,
    PackApprovalState,
    RetractionStatus,
    ReviewDecision,
    ReviewerRole,
    SourceLifecycleState,
)
from synapse.schemas.source import Author, SourceContainer

SEMVER_PATTERN = re.compile(
    r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$"
)  # Strict MAJOR.MINOR.PATCH; no pre-release or build suffixes, so version ordering is unambiguous

PACK_ID_PATTERN = re.compile(
    r"^[a-z][a-z0-9]*(-[a-z0-9]+)*$"
)  # Lowercase kebab-case, e.g. 'diabetes-previsit'. Also used as a directory name, so no separators or spaces.

# States that cannot exist without a review record. Named here rather than
# inlined so the rule reads as one thing and is greppable from both
# enforcement points (this model, and synapse.governance.states).
REVIEW_REQUIRED_LIFECYCLE_STATES = frozenset(
    {SourceLifecycleState.SCREENED, SourceLifecycleState.APPROVED, SourceLifecycleState.REJECTED}
)

_ALLOWED_URL_SCHEMES = (
    "http://",
    "https://",
)  # A canonical URL is rendered as a clickable citation; other schemes are a link-injection surface


# ---------------------------------------------------------------------------
# Review
# ---------------------------------------------------------------------------


class ClinicianReview(SynapseModel):
    """A recorded human review of one source, against one pack's declared scope.

    The six assessment fields are mandatory and free-text-with-a-floor: a
    reviewer must actually write something in each. A review that records only
    a decision is not a review — it is an assertion, and it gives a later
    auditor no way to tell whether the scope was actually considered.
    """

    reviewer_id: str = Field(
        description="Pseudonymous reviewer identifier, 'rev_' + 8 lowercase alphanumerics. Supplied by the operator; NEVER generated by this software."
    )
    reviewer_role: ReviewerRole = Field(
        description="Reviewer's role. Only 'clinician' may approve clinical content for patient-facing use."
    )
    reviewed_at: datetime = Field(description="When the review was recorded (timezone-aware).")
    review_due_at: date = Field(
        description="Date this decision must be revisited. An approval without an expiry silently becomes permanent."
    )
    rubric_version: str = Field(
        min_length=1,
        description="Version of the review rubric applied, so a decision can be interpreted against the standard in force at the time.",
    )

    # -- the six assessment dimensions (requirement 7) ----------------------
    relevance: str = Field(
        min_length=1, description="Is this source relevant to the pack's supported topics?"
    )
    population_applicability: str = Field(
        min_length=1,
        description="Does the study population match the pack's intended patient population?",
    )
    evidence_quality: str = Field(
        min_length=1, description="Assessment of study design, conduct and strength of evidence."
    )
    known_limitations: str = Field(
        min_length=1, description="Limitations a patient-facing answer must not overstate past."
    )
    patient_safety_concerns: str = Field(
        min_length=1,
        description="Safety concerns arising from patient-facing use. 'None identified' is a valid answer; silence is not.",
    )

    decision: ReviewDecision = Field(description="The reviewer's decision.")
    decision_rationale: str = Field(
        min_length=1, description="Why this decision, in the reviewer's own words."
    )

    @field_validator("reviewer_id")
    @classmethod
    def _validate_reviewer_pseudonymity(cls, value: str) -> str:
        """Enforce pseudonymity at the schema boundary.

        The mapping from pseudonym to person is held outside this repository, so
        a clone of a source pack never carries reviewer identities.
        """
        if not is_valid_reviewer_id(value):
            raise ValueError(
                "reviewer_id must match 'rev_' followed by 8 lowercase alphanumeric characters"
            )
        return value

    @field_validator(
        "relevance",
        "population_applicability",
        "evidence_quality",
        "known_limitations",
        "patient_safety_concerns",
        "decision_rationale",
    )
    @classmethod
    def _validate_substantive_text(cls, value: str) -> str:
        """Reject whitespace-only and placeholder answers.

        Without this, a template filled in with "-" or "n/a" would satisfy
        ``min_length=1`` and produce a review that documents nothing.
        """
        stripped = value.strip()
        if not stripped:
            raise ValueError("review fields must not be blank")
        if stripped.lower() in {
            "n/a",
            "na",
            "-",
            "--",
            "tbd",
            "todo",
            "?",
        }:  # Common placeholder tokens; an explicit "None identified" is accepted
            raise ValueError("review fields must contain a substantive answer, not a placeholder")
        return value

    @model_validator(mode="after")
    def _validate_review(self) -> ClinicianReview:
        """Reject naive timestamps and reviews whose expiry precedes the review."""
        require_timezone_aware(self.reviewed_at, "reviewed_at")
        if (
            self.review_due_at < self.reviewed_at.date()
        ):  # An already-expired approval is meaningless
            raise ValueError("review_due_at must not precede reviewed_at")
        return self


# ---------------------------------------------------------------------------
# Sources
# ---------------------------------------------------------------------------


class PackSource(VersionedModel):
    """One source inside a pack: its citation, and its governance standing."""

    SCHEMA_NAME: ClassVar[str] = "pack_source"
    SCHEMA_VERSION: ClassVar[str] = "1.0"

    # -- identity -----------------------------------------------------------
    document_id: str = Field(description="Stable document identifier, '<scheme>:<key>'.")
    canonical_url: str = Field(
        min_length=1,
        description="Exact canonical URL of the source. Not a template, not a search link.",
    )
    pmid: str | None = Field(
        default=None, description="PubMed identifier, when the source has one."
    )
    doi: str | None = Field(
        default=None, description="DOI, normalised to lowercase without a resolver prefix."
    )
    guideline_id: str | None = Field(
        default=None, description="Issuing organisation's guideline identifier, when applicable."
    )

    # -- citation -----------------------------------------------------------
    title: str = Field(
        min_length=1, description="Full title, including any text inside nested markup."
    )
    authors: list[Author] = Field(
        default_factory=list,
        description="Authors as published. Empty when unavailable — never inferred.",
    )
    container: SourceContainer = Field(
        default_factory=SourceContainer,
        description="Journal, or the organisation issuing a guideline.",
    )
    publication_date: date | None = Field(
        default=None, description="Original publication date, when known."
    )
    revision_date: date | None = Field(
        default=None, description="Latest revision date, for guidelines that are revised in place."
    )
    evidence_type: EvidenceType = Field(
        default=EvidenceType.UNCLASSIFIED, description="Normalised evidence class."
    )
    language: str | None = Field(
        default=None, description="Primary language code as published, e.g. 'eng'."
    )

    # -- governance ---------------------------------------------------------
    lifecycle_state: SourceLifecycleState = Field(
        default=SourceLifecycleState.DISCOVERED,
        description="Governance standing. Automation may only ever produce 'discovered'.",
    )
    review: ClinicianReview | None = Field(
        default=None,
        description="Human review record. Required for screened/approved/rejected; forbidden for discovered.",
    )
    exclusion_reason: str | None = Field(
        default=None,
        description="Why this source is excluded. Required for rejected, expired and superseded.",
    )
    superseded_by: str | None = Field(
        default=None, description="Document identifier of the source that replaces this one."
    )
    retraction_status: RetractionStatus = Field(
        default=RetractionStatus.UNCHECKED,
        description="Retraction screening state carried through from ingestion.",
    )

    # -- provenance ---------------------------------------------------------
    content_sha256: str = Field(
        description="SHA-256 of the source's normalised text at the time it entered the pack. Detects the source changing under a completed review."
    )
    discovered_at: datetime = Field(
        description="When automated discovery added this entry (timezone-aware)."
    )
    discovery_method: str = Field(
        min_length=1,
        description="How this source was found, e.g. 'pubmed_esearch' or 'manual_entry'. An approval is only as good as the provenance of what was reviewed.",
    )

    @field_validator("document_id")
    @classmethod
    def _validate_document_id(cls, value: str) -> str:
        """Reject identifiers outside the grammar."""
        if not is_valid_document_id(value):
            raise ValueError("document_id does not match the required '<scheme>:<key>' grammar")
        return value

    @field_validator("canonical_url")
    @classmethod
    def _validate_url_scheme(cls, value: str) -> str:
        """Restrict URLs to http/https, as they are rendered as clickable citations."""
        if not value.startswith(_ALLOWED_URL_SCHEMES):
            raise ValueError("canonical_url must be an http:// or https:// URL")
        return value

    @field_validator("content_sha256")
    @classmethod
    def _validate_digest_shape(cls, value: str) -> str:
        """Reject anything that is not a lowercase 64-character hex digest."""
        if not is_sha256_hex(value):
            raise ValueError("content_sha256 must be 64 lowercase hexadecimal characters")
        return value

    @field_validator("superseded_by")
    @classmethod
    def _validate_superseded_by(cls, value: str | None) -> str | None:
        """A supersession must point at a well-formed identifier."""
        if value is not None and not is_valid_document_id(value):
            raise ValueError("superseded_by must be a well-formed document identifier")
        return value

    @model_validator(mode="after")
    def _validate_lifecycle_invariants(self) -> PackSource:
        """Enforce the automation/approval separation at the record level.

        These are the rules that make "approved" impossible to assert without
        the evidence that licenses it.
        """
        state = self.lifecycle_state

        if state is SourceLifecycleState.DISCOVERED and self.review is not None:
            # A discovered entry carrying a review is contradictory: either it
            # was reviewed (and belongs in a later state) or the record is
            # malformed. Silently allowing it would let a review be attached
            # without advancing the state a reader checks.
            raise ValueError("a 'discovered' source must not carry a review record")

        # The core rule: these three states are human judgements, so each
        # requires the record proving a judgement actually happened.
        if state in REVIEW_REQUIRED_LIFECYCLE_STATES and self.review is None:
            raise ValueError(f"lifecycle_state '{state.value}' requires a review record")

        if state is SourceLifecycleState.APPROVED:
            if (
                self.review is None or self.review.decision is not ReviewDecision.APPROVED
            ):  # A 'needs changes' review cannot license approval
                raise ValueError(
                    "lifecycle_state 'approved' requires a review whose decision is 'approved'"
                )
            if (
                self.review.reviewer_role is not ReviewerRole.CLINICIAN
            ):  # Non-clinical review cannot approve clinical content
                raise ValueError("lifecycle_state 'approved' requires a clinician reviewer")

        if state is SourceLifecycleState.REJECTED:
            if (
                self.review is not None and self.review.decision is ReviewDecision.APPROVED
            ):  # Contradictory: an approving review under a rejected state
                raise ValueError("lifecycle_state 'rejected' must not carry an approving review")
            if (
                not self.exclusion_reason
            ):  # A rejection with no reason cannot be revisited or audited
                raise ValueError("lifecycle_state 'rejected' requires an exclusion_reason")

        if (
            state in (SourceLifecycleState.EXPIRED, SourceLifecycleState.SUPERSEDED)
            and not self.exclusion_reason
        ):
            raise ValueError(f"lifecycle_state '{state.value}' requires an exclusion_reason")

        if (
            state is SourceLifecycleState.SUPERSEDED and not self.superseded_by
        ):  # A supersession that names no successor is untraceable
            raise ValueError("lifecycle_state 'superseded' requires superseded_by")

        require_timezone_aware(self.discovered_at, "discovered_at")
        return self

    @property
    def is_approved(self) -> bool:  # Convenience predicate used by the eligibility layer
        """True only when this source carries a complete clinician approval."""
        return self.lifecycle_state is SourceLifecycleState.APPROVED

    def review_expired_on(self, as_of: date) -> bool:
        """True when an approval's review-due date has passed as of ``as_of``."""
        if self.review is None:  # Nothing to expire
            return False
        return self.review.review_due_at < as_of


# ---------------------------------------------------------------------------
# Pack scope and policy
# ---------------------------------------------------------------------------


class PackScope(SynapseModel):
    """What the pack is for, and — equally importantly — what it is not for.

    ``excluded_uses`` is mandatory and must be non-empty. A scope that states
    only what a pack is for is not a scope: the boundary is the part that makes
    a review decision possible, because a reviewer must know which questions
    they are *not* approving the pack to answer.
    """

    intended_patient_population: str = Field(
        min_length=1,
        description="Who this pack's sources are appropriate for, e.g. 'adults aged 18+ with an existing type 2 diabetes diagnosis'.",
    )
    intended_use: str = Field(
        min_length=1,
        description="What the pack is approved to support, e.g. 'pre-visit patient education and question preparation'.",
    )
    excluded_uses: list[str] = Field(
        min_length=1,
        description="Uses this pack is explicitly NOT approved for. Must be non-empty.",
    )
    supported_topics: list[str] = Field(
        min_length=1,
        description="Topic boundaries the pack covers. A query outside these is out of scope.",
    )
    out_of_scope_topics: list[str] = Field(
        default_factory=list,
        description="Topics deliberately excluded, recorded so the boundary is explicit rather than merely implied.",
    )


class SourceSelectionPolicy(SynapseModel):
    """The rule by which sources were selected, recorded so it can be audited."""

    description: str = Field(
        min_length=1, description="Human-readable statement of the selection strategy."
    )
    discovery_queries: list[str] = Field(
        default_factory=list,
        description="Search expressions used for automated discovery, verbatim.",
    )
    minimum_evidence_types: list[EvidenceType] = Field(
        min_length=1,
        description="Evidence classes a source must belong to in order to be eligible for approval.",
    )
    maximum_age_years: int | None = Field(
        default=None,
        gt=0,
        description="Sources older than this require explicit reviewer justification. Null means no age limit is applied.",
    )
    required_languages: list[str] = Field(
        default_factory=lambda: ["eng"], description="Language codes accepted into the pack."
    )
    exclude_retracted: bool = Field(
        default=True,
        description="Whether retracted and expression-of-concern sources are excluded. Defaults to true.",
    )
    exclude_preprints: bool = Field(
        default=True,
        description="Whether non-peer-reviewed preprints are excluded. Defaults to true for patient-facing use.",
    )


class ReviewerRequirements(SynapseModel):
    """Who is qualified to approve this pack, and under which rubric."""

    required_role: ReviewerRole = Field(
        default=ReviewerRole.CLINICIAN,
        description="Minimum reviewer role required to approve a source in this pack.",
    )
    minimum_reviewers_per_source: int = Field(
        default=1,
        ge=1,
        description="How many independent reviews each source needs before approval.",
    )
    rubric_version: str = Field(
        min_length=1, description="Version of the review rubric reviewers must apply."
    )
    review_interval_days: int = Field(
        default=365,
        gt=0,
        description="Maximum time between reviews. Drives the review-due date on every approval.",
    )
    separation_of_duties: str = Field(
        default="The reviewer of a source must not be the person who configured its discovery query.",
        description="The separation-of-duties rule in force for this pack, recorded so it can be audited.",
    )


# ---------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------


class SourcePackManifest(VersionedModel):
    """The pack's governance record: scope, policy, approval state and integrity."""

    SCHEMA_NAME: ClassVar[str] = "source_pack_manifest"
    SCHEMA_VERSION: ClassVar[str] = (
        "2.0"  # 2.0 replaces the earlier summary-only manifest with a governed one; a MAJOR bump because required fields were added
    )

    # -- identity -----------------------------------------------------------
    pack_id: str = Field(
        description="Stable pack identifier, lowercase kebab-case, e.g. 'diabetes-previsit'."
    )
    version: str = Field(description="Semantic version, MAJOR.MINOR.PATCH.")
    title: str = Field(min_length=1, description="Human-readable pack name.")
    description: str = Field(min_length=1, description="What this pack contains and why it exists.")

    # -- scope and policy ---------------------------------------------------
    scope: PackScope = Field(
        description="Intended population, intended use, excluded uses and topic boundaries."
    )
    selection_policy: SourceSelectionPolicy = Field(
        description="How sources were selected, and the minimum evidence requirements."
    )
    reviewer_requirements: ReviewerRequirements = Field(
        description="Who may approve, under which rubric, and how often review recurs."
    )

    # -- approval -----------------------------------------------------------
    approval_state: PackApprovalState = Field(
        default=PackApprovalState.DRAFT,
        description="Governance state of the whole pack. Defaults to draft.",
    )
    approved_at: datetime | None = Field(
        default=None,
        description="When the pack was approved. Required for 'approved', forbidden otherwise.",
    )
    approved_by: str | None = Field(
        default=None,
        description="Pseudonymous identifier of the approving reviewer. Never generated by this software.",
    )
    review_due_at: date | None = Field(
        default=None,
        description="When the pack approval must be revisited. Required for 'approved'.",
    )
    superseded_by_version: str | None = Field(
        default=None, description="Version that replaces this one, when superseded."
    )

    # -- integrity ----------------------------------------------------------
    corpus_sha256: str = Field(
        description="Order-sensitive digest over the serialised sources. Any content change alters it, which is what forces a version bump."
    )
    source_count: int = Field(ge=0, description="Number of sources in the pack.")
    lifecycle_counts: dict[str, int] = Field(
        default_factory=dict,
        description="Source counts per lifecycle state. Always carries every state, so a reader can see at a glance that nothing is approved.",
    )

    # -- provenance ---------------------------------------------------------
    build_tool_version: str = Field(
        min_length=1, description="Version of the tool that produced this manifest."
    )
    created_at: datetime = Field(description="When the pack was first created (timezone-aware).")
    updated_at: datetime = Field(description="When the manifest was last written (timezone-aware).")
    notes: str = Field(
        default="", description="Operational notes. Must not contain clinical assertions."
    )

    @field_validator("pack_id")
    @classmethod
    def _validate_pack_id(cls, value: str) -> str:
        """Pack identifiers double as directory names, so the grammar is strict."""
        if not PACK_ID_PATTERN.match(value):
            raise ValueError("pack_id must be lowercase kebab-case, e.g. 'diabetes-previsit'")
        return value

    @field_validator("version", "superseded_by_version")
    @classmethod
    def _validate_semver(cls, value: str | None) -> str | None:
        """Strict MAJOR.MINOR.PATCH, so versions order unambiguously."""
        if value is not None and not SEMVER_PATTERN.match(value):
            raise ValueError("version must be a semantic version, MAJOR.MINOR.PATCH")
        return value

    @field_validator("corpus_sha256")
    @classmethod
    def _validate_digest_shape(cls, value: str) -> str:
        """Reject anything that is not a lowercase 64-character hex digest."""
        if not is_sha256_hex(value):
            raise ValueError("corpus_sha256 must be 64 lowercase hexadecimal characters")
        return value

    @field_validator("approved_by")
    @classmethod
    def _validate_approver(cls, value: str | None) -> str | None:
        """The approver must be a pseudonymous identifier supplied by an operator."""
        if value is not None and not is_valid_reviewer_id(value):
            raise ValueError(
                "approved_by must match 'rev_' followed by 8 lowercase alphanumeric characters"
            )
        return value

    @model_validator(mode="after")
    def _validate_approval_invariants(self) -> SourcePackManifest:
        """Enforce that an approval claim carries all of its required evidence.

        This is requirement 5's first rule in its strongest form: the
        ``approved`` state is simply not constructible without the fields that
        make it meaningful and revocable.
        """
        if self.approval_state is PackApprovalState.APPROVED:
            missing = [
                name
                for name, value in (
                    ("approved_at", self.approved_at),
                    ("approved_by", self.approved_by),
                    ("review_due_at", self.review_due_at),
                )
                if value is None
            ]
            if missing:  # Reported together so an operator fixes them in one pass
                raise ValueError(f"approval_state 'approved' requires: {', '.join(missing)}")
            if self.source_count == 0:  # An approved pack with no sources approves nothing
                raise ValueError("approval_state 'approved' requires at least one source")
        else:
            # The converse matters just as much: approval metadata lingering on
            # a draft would make a later reader believe a decision exists.
            for name, value in (
                ("approved_at", self.approved_at),
                ("approved_by", self.approved_by),
            ):
                if value is not None:
                    raise ValueError(f"{name} must be null unless approval_state is 'approved'")

        if self.approval_state is PackApprovalState.SUPERSEDED and not self.superseded_by_version:
            raise ValueError("approval_state 'superseded' requires superseded_by_version")

        require_timezone_aware(self.created_at, "created_at")
        require_timezone_aware(self.updated_at, "updated_at")
        if self.approved_at is not None:
            require_timezone_aware(self.approved_at, "approved_at")
        if self.updated_at < self.created_at:  # Usually a timezone bug rather than time travel
            raise ValueError("updated_at must not precede created_at")
        if self.lifecycle_counts and sum(self.lifecycle_counts.values()) != self.source_count:
            raise ValueError("lifecycle_counts must sum to source_count")
        return self

    @property
    def is_example(
        self,
    ) -> bool:  # Used by the eligibility layer to refuse demonstration content outright
        """True when this pack is demonstration content."""
        return self.approval_state is PackApprovalState.UNAPPROVED_EXAMPLE


__all__ = [
    "PACK_ID_PATTERN",
    "REVIEW_REQUIRED_LIFECYCLE_STATES",
    "SEMVER_PATTERN",
    "ClinicianReview",
    "PackScope",
    "PackSource",
    "ReviewerRequirements",
    "SourcePackManifest",
    "SourceSelectionPolicy",
]
