/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Alive. Says nothing about whether an artifact loaded.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Ready only when every startup gate passed and a service exists.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/access/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange the passcode
         * @description Verify the shared passcode and open a session.
         */
        post: operations["login_v1_access_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/access/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session
         * @description Discard the session and clear the cookie.
         *
         *     Idempotent, and deliberately never reports whether a session existed: that
         *     would confirm a guessed identifier. The cookie is cleared either way.
         */
        post: operations["logout_v1_access_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session state
         * @description Counts and clocks only. No conversation content, ever.
         */
        get: operations["read_session_v1_session_get"];
        put?: never;
        post?: never;
        /**
         * Discard the session
         * @description Forget everything held for this session.
         */
        delete: operations["delete_session_v1_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transparency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What this deployment runs
         * @description Sources, evaluation, privacy and system metadata, with disclosures.
         */
        get: operations["transparency_v1_transparency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask one question, streamed
         * @description Run one turn and stream its progress, then its single envelope.
         */
        post: operations["stream_v1_turns_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_index}/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the brief
         * @description Build the brief on first access, then return the stored one.
         */
        get: operations["read_brief_v1_turns__turn_index__brief_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_index}/brief/export/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the brief
         * @description Render the brief and return it as an attachment.
         *
         *     Built in memory and streamed out. Nothing touches disk.
         */
        get: operations["export_brief_v1_turns__turn_index__brief_export__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_index}/brief/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the notes
         * @description The patient's own notes.
         */
        put: operations["put_notes_v1_turns__turn_index__brief_notes_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_index}/brief/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a question
         * @description Add a question the patient wrote. Marked as theirs, never as evidence.
         */
        post: operations["post_question_v1_turns__turn_index__brief_questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_index}/brief/questions/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reorder questions
         * @description Reorder by identifier. The set must match exactly; nothing is added here.
         */
        put: operations["put_question_order_v1_turns__turn_index__brief_questions_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_index}/brief/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a question
         * @description Remove one question by identifier.
         */
        delete: operations["delete_question_v1_turns__turn_index__brief_questions__question_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_index}/brief/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Choose sections
         * @description Choose which sections the export includes.
         *
         *     The disclaimer is always included and cannot be removed — the section list
         *     the schema exposes does not contain it.
         */
        put: operations["put_sections_v1_turns__turn_index__brief_sections_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_index}/brief/topic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the topic
         * @description The patient's own 'what I want to talk about' line.
         */
        put: operations["put_topic_v1_turns__turn_index__brief_topic_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerEnvelope
         * @description A validated answer. ``action`` distinguishes the three answer states.
         */
        AnswerEnvelope: {
            /**
             * Action
             * @enum {string}
             */
            action: "answer" | "abstain" | "medical_staff";
            /**
             * Brief Available
             * @description Whether an appointment brief can be built from this turn.
             */
            brief_available: boolean;
            /** Claims */
            claims: components["schemas"]["ClaimModel"][];
            /**
             * Disclaimer
             * @description Application-owned. No model contributes to it.
             */
            disclaimer: string;
            /** Doctor Evaluation */
            doctor_evaluation: string;
            /** Excerpts */
            excerpts: components["schemas"]["ExcerptModel"][];
            /** @description Populated on an abstention, which IS the insufficient state. */
            insufficient?: components["schemas"]["InsufficientModel"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "answer";
            /** Limitations */
            limitations: string[];
            /** Questions For Doctor */
            questions_for_doctor: string[];
            /**
             * Resolved Query
             * @description What a follow-up was resolved to for retrieval. Empty unless a rewrite actually happened. Model-generated: render as text.
             * @default
             */
            resolved_query: string;
            /** Sources */
            sources: components["schemas"]["SourceModel"][];
            /**
             * Staff Message
             * @description Set only for the medical_staff action; application copy.
             * @default
             */
            staff_message: string;
            /** Summary */
            summary: string;
            /** Turn Index */
            turn_index: number;
        };
        /**
         * BriefClaimModel
         * @description One claim in the brief, with its support level.
         */
        BriefClaimModel: {
            /** Claim Id */
            claim_id: string;
            /** Included */
            included: boolean;
            /** Source Numbers */
            source_numbers: number[];
            /** Support */
            support: string;
            /** Text */
            text: string;
        };
        /**
         * BriefNotesRequest
         * @description Replace the patient's own notes.
         */
        BriefNotesRequest: {
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /**
         * BriefQuestionModel
         * @description One question in the brief, with where it came from.
         */
        BriefQuestionModel: {
            /**
             * Origin
             * @description Whether the patient or the system wrote it.
             */
            origin: string;
            /** Question Id */
            question_id: string;
            /** Text */
            text: string;
        };
        /**
         * BriefQuestionOrderRequest
         * @description Reorder the questions by identifier.
         */
        BriefQuestionOrderRequest: {
            /** Order */
            order: string[];
        };
        /**
         * BriefQuestionRequest
         * @description Add one question the patient wrote themselves.
         */
        BriefQuestionRequest: {
            /** Text */
            text: string;
        };
        /**
         * BriefResponse
         * @description The server-owned brief. A client edits it by named operation only.
         */
        BriefResponse: {
            /** Available Sections */
            available_sections: string[];
            /** Claims */
            claims: components["schemas"]["BriefClaimModel"][];
            /** Disclaimer */
            disclaimer: string;
            /** Document Id */
            document_id: string;
            /** Export Warning */
            export_warning: string;
            /** Fill Ratio */
            fill_ratio: number;
            /** Fits One Page */
            fits_one_page: boolean;
            /** Included Sections */
            included_sections: string[];
            /** Notes */
            notes: string;
            /** Overflow Advice */
            overflow_advice: string[];
            /** Questions */
            questions: components["schemas"]["BriefQuestionModel"][];
            /** Sources */
            sources: components["schemas"]["SourceModel"][];
            /** Topic */
            topic: string;
            /** Turn Index */
            turn_index: number;
        };
        /**
         * BriefSectionsRequest
         * @description Choose which sections the export includes.
         */
        BriefSectionsRequest: {
            /** Sections */
            sections: string[];
        };
        /**
         * BriefTopicRequest
         * @description Replace the patient's own 'what I want to talk about' line.
         */
        BriefTopicRequest: {
            /**
             * Topic
             * @default
             */
            topic: string;
        };
        /**
         * ClaimModel
         * @description One displayed claim. Withheld claims never appear here at all.
         */
        ClaimModel: {
            /** Claim Id */
            claim_id: string;
            /** Source Numbers */
            source_numbers: number[];
            /**
             * Support
             * @description Partial support is shown and marked, never silently corrected.
             * @enum {string}
             */
            support: "supported" | "partially_supported";
            /** Text */
            text: string;
        };
        /**
         * DeletedResponse
         * @description Confirmation that state was discarded.
         */
        DeletedResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /**
         * EmergencyEnvelope
         * @description A red flag. Produced before retrieval, so it cites nothing.
         */
        EmergencyEnvelope: {
            /**
             * Brief Available
             * @default false
             * @constant
             */
            brief_available: false;
            /** Disclaimer */
            disclaimer: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "emergency";
            /**
             * Message
             * @description Application copy. The one state that should interrupt.
             */
            message: string;
            /** Turn Index */
            turn_index: number;
        };
        /**
         * ExcerptModel
         * @description A verbatim span the verifier matched, under its source's number.
         */
        ExcerptModel: {
            /** Chunk Id */
            chunk_id: string;
            /** Quote */
            quote: string;
            /** Source Number */
            source_number: number;
        };
        /**
         * FailureEnvelope
         * @description A fault. Fixed copy plus a typed code, and nothing else, ever.
         */
        FailureEnvelope: {
            /**
             * Brief Available
             * @default false
             * @constant
             */
            brief_available: false;
            /**
             * Code
             * @description A closed AnswerFailureCode value.
             */
            code: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "failure";
            /**
             * Message
             * @description The single patient-facing message, identical for every code.
             */
            message: string;
            /** Turn Index */
            turn_index: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness. Says nothing about whether the artifact loaded.
         */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * InsufficientEnvelope
         * @description No verified evidence. A designed state, not an error.
         */
        InsufficientEnvelope: {
            /**
             * Brief Available
             * @default false
             * @constant
             */
            brief_available: false;
            detail: components["schemas"]["InsufficientModel"];
            /** Disclaimer */
            disclaimer: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "insufficient";
            /** Turn Index */
            turn_index: number;
        };
        /**
         * InsufficientModel
         * @description The complete patient-facing content for the insufficient-evidence state.
         */
        InsufficientModel: {
            /** Heading */
            heading: string;
            /** Message */
            message: string;
            /** Next Steps */
            next_steps: string[];
            /**
             * Not A Judgement
             * @description Prevents 'we found nothing' being read as 'there is nothing wrong'.
             */
            not_a_judgement: string;
            /**
             * Reason
             * @description Operator-facing reason code.
             */
            reason: string;
        };
        /**
         * LoginRequest
         * @description The shared passcode, exchanged for an access token.
         */
        LoginRequest: {
            /**
             * Passcode
             * @description The shared access passcode.
             */
            passcode: string;
        };
        /**
         * LoginResponse
         * @description A new session. The token is also set as an HttpOnly cookie.
         */
        LoginResponse: {
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Session Id */
            session_id: string;
        };
        /**
         * ReadyResponse
         * @description Readiness. ``ready`` is false until every startup gate has passed.
         */
        ReadyResponse: {
            /** Artifact */
            artifact?: {
                [key: string]: unknown;
            };
            /**
             * Detail
             * @description An exception TYPE name. Never a message.
             * @default
             */
            detail: string;
            /** Failure Code */
            failure_code?: string | null;
            /** Ready */
            ready: boolean;
            /** State */
            state: string;
        };
        /**
         * SessionResponse
         * @description What the server holds for this session. No conversation content.
         */
        SessionResponse: {
            /** Idle Ttl Seconds */
            idle_ttl_seconds: number;
            /** Max Turns */
            max_turns: number;
            /** Session Id */
            session_id: string;
            /** Turn Active */
            turn_active: boolean;
            /** Turn Count */
            turn_count: number;
        };
        /**
         * SourceModel
         * @description One numbered source, as it appears inline and in the source panel.
         */
        SourceModel: {
            /**
             * Number
             * @description Stable display number, assigned from retrieval order.
             */
            number: number;
            /**
             * Relevance
             * @description Retrieval relevance, 0..1. NOT a confidence and NOT a quality grade.
             */
            relevance?: number | null;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /**
             * Url
             * @description Empty when the recorded link was not http(s).
             */
            url: string;
        };
        /**
         * StreamedTurnEnvelope
         * @description The payload of the single terminal ``envelope`` server-sent event.
         *
         *     A wrapper exists only so the union reaches the OpenAPI document. The stream
         *     route returns an SSE body rather than a JSON model, and without something
         *     declared as its response the four envelope schemas would never be emitted
         *     into ``components`` — leaving a generated client with no type for the one
         *     message that matters.
         */
        StreamedTurnEnvelope: components["schemas"]["AnswerEnvelope"] | components["schemas"]["EmergencyEnvelope"] | components["schemas"]["InsufficientEnvelope"] | components["schemas"]["FailureEnvelope"];
        /**
         * TransparencyResponse
         * @description What this deployment is running, and what it has NOT been shown to be.
         */
        TransparencyResponse: {
            /** Application Version */
            application_version: string;
            /**
             * Disclosures
             * @description Mandatory statements. Never empty; never softened by configuration.
             */
            disclosures: string[];
            /** Evaluation */
            evaluation: {
                [key: string]: unknown;
            };
            /** Privacy */
            privacy: {
                [key: string]: unknown;
            };
            /** Sources */
            sources: {
                [key: string]: unknown;
            };
            /** System */
            system: {
                [key: string]: unknown;
            };
        };
        /**
         * TurnRequest
         * @description One patient question.
         *
         *     ``query`` is unrestricted free text by design — a patient must be able to
         *     describe a symptom in their own words. It is bounded in *length* only, and
         *     the interface carries a persistent warning not to enter identifiers.
         */
        TurnRequest: {
            /**
             * Client Request Id
             * @description Client-generated id for idempotent retry. Re-sending the same id replays the previous result instead of running a second turn.
             * @default
             */
            client_request_id: string;
            /**
             * Query
             * @description The patient's question, in their own words.
             */
            query: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    login_v1_access_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_access_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedResponse"];
                };
            };
        };
    };
    read_session_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    delete_session_v1_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedResponse"];
                };
            };
        };
    };
    transparency_v1_transparency_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransparencyResponse"];
                };
            };
        };
    };
    stream_v1_turns_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description An SSE stream: zero or more `stage` events, then EXACTLY ONE `envelope` event whose `data` is the schema below. No medical content is emitted before validation and verification finish. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamedTurnEnvelope"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_brief_v1_turns__turn_index__brief_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Zero-based index of the turn. */
                turn_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_brief_v1_turns__turn_index__brief_export__fmt__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fmt: string;
                /** @description Zero-based index of the turn. */
                turn_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_notes_v1_turns__turn_index__brief_notes_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Zero-based index of the turn. */
                turn_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefNotesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_question_v1_turns__turn_index__brief_questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Zero-based index of the turn. */
                turn_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_question_order_v1_turns__turn_index__brief_questions_order_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Zero-based index of the turn. */
                turn_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefQuestionOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_question_v1_turns__turn_index__brief_questions__question_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
                /** @description Zero-based index of the turn. */
                turn_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_sections_v1_turns__turn_index__brief_sections_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Zero-based index of the turn. */
                turn_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefSectionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_topic_v1_turns__turn_index__brief_topic_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Zero-based index of the turn. */
                turn_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefTopicRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
