import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import type { Brief, Transparency, TurnEnvelope } from "@/lib/envelope";

/**
 * The golden fixtures, read from disk.
 *
 * These files are **generated by the Python test suite** from
 * `tests/golden_states.py`, through the same `envelope_for` the streaming route
 * calls (`tests/frontend_fixtures.py`). They are not written by hand, and
 * editing one by hand accomplishes nothing: `tests/test_frontend_fixtures.py`
 * regenerates and compares them, so a hand edit fails the Python gate.
 *
 * Read from disk rather than imported so that a fixture added on the Python
 * side is picked up by `everyEnvelope()` without anyone remembering to add an
 * import here. A state that exists on the server but has no screen is exactly
 * the failure this arrangement is meant to catch, so discovery has to be
 * automatic or it does not catch it.
 */

const DIR = join(process.cwd(), "tests", "fixtures");

function read<T>(name: string): T {
  return JSON.parse(readFileSync(join(DIR, `${name}.json`), "utf8")) as T;
}

/** One envelope by its golden-state name, e.g. `"answer"`, `"emergency"`. */
export function envelope(state: string): TurnEnvelope {
  return read<TurnEnvelope>(`envelope.${state}`);
}

/** Every envelope fixture, as `[stateName, envelope]`, sorted for stable output. */
export function everyEnvelope(): [string, TurnEnvelope][] {
  return readdirSync(DIR)
    .filter((file) => file.startsWith("envelope.") && file.endsWith(".json"))
    .map((file) => file.slice("envelope.".length, -".json".length))
    .sort()
    .map((state) => [state, envelope(state)]);
}

export const brief = (): Brief => read<Brief>("brief");
export const transparency = (): Transparency => read<Transparency>("transparency");
